# version of docker-compose
version: '3'
# 'services' are equivalent to 'containers'
services:
  redis_socket_1:
    image: 'redis:latest'
    networks:
      - socket_network

  socket_1:
    restart: on-failure
    build: ./socket/socket_1
    ports:
      - '5001:5001'
    depends_on:
      - redis_socket_1
    networks:
      - socket_network

  socket_2:
    restart: on-failure
    build: ./socket/socket_2
    ports:
      - '5002:5001'
    depends_on:
      - redis_socket_1
    networks:
      - socket_network

  socket_client:
    restart: on-failure
    build: ./socket_client
    ports:
      - '3000:3000'

  redis_registry:
    image: 'redis:latest'
    networks:
      - service_registry_network

  service_registry_1:
    restart: on-failure
    build: ./service_registry_1
    environment:
      - redis_host=redis_registry
    depends_on:
      - redis_registry
      - socket_1
    networks:
      - service_registry_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - service_registry_1
    networks:
      - service_registry_network

networks:
  service_registry_network:
    driver: bridge
  socket_network:
    driver: bridge
